version: 2.1

orbs:
  node: circleci/node@4.1
  maven: circleci/maven@1.2.0

jobs:
  build-and-test-for-node:
    docker:
      - image: cimg/node:12.19.0

    working_directory: ~/project

    steps:
      # - checkout
      - run: ls
      # - run: npm start

  # build-and-test-for-maven:
  #   docker:
  #     - image: cimg/openjdk:1.8

  #   working_directory: ~/BackEnd/loginmicroservices

  #   steps:
  #     - checkout
  #     - run: mvn clean install
  #     - run: mvn test

workflows:
  sample:
    jobs:
      - build-and-test-for-node

      # - build-and-test-for-maven
