version: 2.1

orbs:
  node: circleci/node@4.1
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.7.0

jobs:
  test-for-node:
    docker:
      - image: cimg/node:12.19.0

    working_directory: ~/app

    steps:
      - checkout
      - run: cd FrontEnd/myfirstapp && npm install
      - run: cd FrontEnd/myfirstapp && npm test

  run-docker-container-node:
    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Frontend Docker Image
          command: |
            cd FrontEnd/myfirstapp && docker-compose -f docker-compose.dev.yml up

  test-for-maven-login:
    docker:
      - image: cimg/openjdk:11.0

    working_directory: ~/app

    steps:
      - checkout
      - run: cd BackEnd/loginmicroservices && mvn -B -DskipTests clean package
      - run: cd BackEnd/loginmicroservices && mvn test

  run-docker-container-login:
    docker:
      - image: cimg/openjdk:11.0
    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run: cd BackEnd/loginmicroservices && mvn -B -DskipTests clean package
      - run:
          name: Build Frontend Docker Image
          command: |
            cd BackEnd/loginmicroservices && docker build -t loginservices:latest .

  test-for-maven-book:
    docker:
      - image: cimg/openjdk:11.0

    working_directory: ~/app

    steps:
      - checkout
      - run: cd BackEnd/bookservices && mvn -B -DskipTests clean package
      - run: cd BackEnd/bookservices && mvn test

  run-docker-container-book:
    docker:
      - image: cimg/openjdk:11.0
    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run: cd BackEnd/loginmicroservices && mvn -B -DskipTests clean package
      - run:
          name: Build Frontend Docker Image
          command: |
            cd BackEnd/loginmicroservices && docker build -t bookservices:latest .

workflows:
  sample:
    jobs:
      - test-for-node

      - test-for-maven-login

      - test-for-maven-book

      - run-docker-container-node:
          requires:
            - test-for-node

      - run-docker-container-login:
          requires:
            - test-for-maven-login

      - run-docker-container-book:
          requires:
            - test-for-maven-book
