version: 2.1

orbs:
  node: circleci/node@4.1
  maven: circleci/maven@1.2.0

jobs:
  build-and-test-for-node:
    docker:
      - image: cimg/node:15.1

    working_directory: ~/FrontEnd/myfirstapp/

    steps:
      - run: npm install
      - run:
          name: Run Node Tests
          command: npm test

  # build-and-test-for-maven:
  #   docker:
  #     - image: cimg/openjdk:11.0

  #   working_directory: ~/BackEnd/loginmicroservices

  #   steps:
  #     - run:
  #         name: Build
  #         command: mvn clean install
  #     - run:
  #         name: Run Maven Test
  #         command: mvn test

workflows:
  sample:
    jobs:
      - build-and-test-for-node

      # - build-and-test-for-maven
