version: 2.1

orbs:
  node: circleci/node@4.1
  maven: circleci/maven@1.2.0

jobs:
  build-and-test-for-node:
    docker:
      - image: cimg/node:12.19.0

    steps:
      - checkout
      - run: cd /FrontEnd/myfirstapp && npm install
      - run: cd /FrontEnd/myfirstapp && npm test

  build-and-test-for-maven:
    docker:
      - image: cimg/openjdk:1.8

    steps:
      - checkout
      - run: cd BackEnd/loginmicrosevices && mvn clean install
      - run: cd BackEnd/loginmicrosevices && mvn test

workflows:
  sample:
    jobs:
      - build-and-test-for-node

      - build-and-test-for-maven
