version: 2.1

orbs:
  node: circleci/node@4.1
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.7.0

jobs:
  test-run-container-node:
    docker:
      - image: cimg/node:12.19.0

    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run: cd FrontEnd/myfirstapp && npm install
      - run:
          name: Test Frontend with Testing Library
          command: |
            cd FrontEnd/myfirstapp && npm test
      - run:
          name: Build Frontend Docker Image
          command: |
            cd FrontEnd/myfirstapp && docker-compose -f docker-compose.dev.yml build

  test-run-container-login:
    docker:
      - image: cimg/openjdk:11.0

    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run: cd BackEnd/loginmicroservices && mvn -B -DskipTests clean package
      - run:
          name: Test Backend - loginservices
          command: |
            cd BackEnd/loginmicroservices && mvn test
      - run:
          name: Build Frontend Docker Image
          command: |
            cd BackEnd/loginmicroservices && docker build -t loginservices:latest .

  test-run-container-book:
    docker:
      - image: cimg/openjdk:11.0

    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run: cd BackEnd/bookservices && mvn -B -DskipTests clean package
      - run:
          name: Test Backend - bookservices
          command: |
            cd BackEnd/bookservices && mvn test
      - run:
          name: Build Frontend Docker Image
          command: |
            cd BackEnd/bookservices && docker build -t bookservices:latest .

workflows:
  sample:
    jobs:
      - test-run-container-node

      - test-run-container-login

      - test-run-container-book
