version: "3.8"

services:
  app:
    container_name: front-dev
    image: front-dev
    build:
      context: .
      target: development
    stdin_open: true
    networks:
      - sept-network
    ports:
      - 3000:3000

networks:
  sept-network:
    external: true
    name: sept
