version: "3.8"

services:
  app:
    container_name: front-dev:latest
    image: front-dev
    build:
      context: .
      target: development
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
